version: '3'

services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app

  app:
    container_name: "docker-php-unit"
    build: .
    working_dir: /var/www/
    stdin_open: true
    tty: true
    volumes:
      - ../:/var/www/
    env_file: .env